import { useCallback, useEffect, useState } from "react";
import toast from "react-hot-toast";
import { Edit3, Images, Loader2, Plus, Search, Trash2, Upload } from "lucide-react";
import api from "../../../services/api";
import Modal from "../../components/Modal";
import Loading from "../../components/Loading";
import Pagination from "../../components/Pagination";
import StatusBadge from "../../components/StatusBadge";
import { Field, inputClass, selectClass, textareaClass } from "../../components/form";
import compressImageForUpload from "../../../utils/compressImageForUpload";
import displayImageUrl from "../../../utils/displayImageUrl";

const blank = { title: "", category: "Corporate", type: "image", mediaUrl: "", posterUrl: "", altText: "", description: "", order: 0, status: "draft" };

export default function GalleryManagement() {
  const [items, setItems] = useState([]), [loading, setLoading] = useState(true), [page, setPage] = useState(1), [pages, setPages] = useState(1), [total, setTotal] = useState(0);
  const [query, setQuery] = useState(""), [search, setSearch] = useState(""), [modal, setModal] = useState(false), [editing, setEditing] = useState(null), [form, setForm] = useState(blank), [saving, setSaving] = useState(false), [uploading, setUploading] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const { data } = await api.get("/admin/gallery", { params: { page, limit: 10, ...(search ? { search } : {}) } }); setItems(data.data || []); setPages(data.pagination?.pages || 1); setTotal(data.pagination?.total || 0); } catch (e) { toast.error(e.response?.data?.message || "Failed to load gallery"); } finally { setLoading(false); } }, [page, search]);
  useEffect(() => { load(); }, [load]);
  const open = (item) => { setEditing(item || null); setForm(item ? { ...blank, ...item } : blank); setModal(true); };
  const set = (key) => (event) => setForm((old) => ({ ...old, [key]: event.target.value }));
  const upload = async (file, field, input) => { if (!file) return; setUploading(field); try { const prepared = await compressImageForUpload(file); const body = new FormData(); body.append("image", prepared); const { data } = await api.post("/upload/image", body); setForm((old) => ({ ...old, [field]: data.data.url })); toast.success("Image uploaded"); } catch (e) { toast.error(e.response?.data?.message || e.message || "Upload failed"); } finally { setUploading(""); if (input) input.value = ""; } };
  const save = async (event) => { event.preventDefault(); setSaving(true); try { const payload = { ...form, order: Number(form.order) || 0, posterUrl: form.type === "video" ? form.posterUrl : "" }; if (editing) await api.put(`/admin/gallery/${editing._id}`, payload); else await api.post("/admin/gallery", payload); toast.success(editing ? "Gallery item updated" : "Gallery item created"); setModal(false); load(); } catch (e) { toast.error(e.response?.data?.message || "Could not save gallery item"); } finally { setSaving(false); } };
  const remove = async (item) => { if (!window.confirm(`Move “${item.title}” to the recycle bin?`)) return; try { await api.delete(`/admin/gallery/${item._id}`); toast.success("Gallery item deleted"); load(); } catch (e) { toast.error(e.response?.data?.message || "Could not delete item"); } };
  const imageField = (field, label) => { const id = `gallery-${field}-upload`; return <Field label={label} required><div className="space-y-2">{form[field] && <img src={displayImageUrl(form[field])} alt="Preview" className="w-full h-36 object-cover rounded-lg border border-slate-200" />}<div className="flex gap-2"><input className={inputClass} type="url" value={form[field]} onChange={set(field)} placeholder="https://…" required /><input id={id} type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/avif" hidden onChange={(e) => upload(e.target.files?.[0], field, e.target)} /><button type="button" disabled={!!uploading} onClick={() => document.getElementById(id)?.click()} className="shrink-0 px-4 rounded-lg border border-slate-300 text-sm font-semibold text-[#092f3b]">{uploading === field ? <Loader2 className="w-4 h-4 animate-spin" /> : <Upload className="w-4 h-4" />}</button></div></div></Field>; };
  return <div className="admin-page">
    <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6"><div><h1 className="text-xl font-extrabold text-[#092f3b]">Media Gallery</h1><p className="text-sm text-[#66767d] mt-1">Manage photos and embedded videos published at /gallery.</p></div><button onClick={() => open()} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg bg-[#dc2626] text-white text-sm font-semibold"><Plus className="w-4 h-4" /> New media</button></div>
    <div className="relative mb-4 max-w-md"><Search className="absolute left-3 top-3.5 w-4 h-4 text-slate-400" /><input className={`${inputClass} pl-10`} value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") { setSearch(query); setPage(1); } }} placeholder="Search gallery…" /></div>
    {loading ? <Loading label="Loading gallery…" /> : <><div className="bg-white border border-slate-200 rounded-xl overflow-x-auto"><table className="w-full text-left"><thead className="bg-slate-50 text-[11px] uppercase text-[#66767d]"><tr><th className="px-4 py-3">Media</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody>{items.length ? items.map((item) => <tr key={item._id} className="border-t border-slate-100"><td className="px-4 py-3"><div className="flex items-center gap-3"><img className="w-16 h-12 rounded object-cover bg-slate-100" src={displayImageUrl(item.type === "video" ? item.posterUrl : item.mediaUrl)} alt="" /><div><b className="text-sm text-[#092f3b]">{item.title}</b><p className="text-xs text-slate-400">Order {item.order || 0}</p></div></div></td><td className="px-4 py-3 text-sm text-slate-600">{item.category}</td><td className="px-4 py-3 text-sm capitalize text-slate-600">{item.type}</td><td className="px-4 py-3"><StatusBadge status={item.status} /></td><td className="px-4 py-3 text-right"><button className="p-2 text-slate-500" onClick={() => open(item)} aria-label={`Edit ${item.title}`}><Edit3 className="w-4 h-4" /></button><button className="p-2 text-red-600" onClick={() => remove(item)} aria-label={`Delete ${item.title}`}><Trash2 className="w-4 h-4" /></button></td></tr>) : <tr><td colSpan="5" className="py-14 text-center text-slate-500"><Images className="w-10 h-10 mx-auto mb-2 text-slate-300" />No gallery items found.</td></tr>}</tbody></table></div><Pagination page={page} totalPages={pages} total={total} pageSize={10} currentCount={items.length} onPageChange={setPage} /></>}
    <Modal open={modal} onClose={() => setModal(false)} title={editing ? "Edit gallery item" : "New gallery item"} size="lg"><form onSubmit={save} className="space-y-4"><div className="grid sm:grid-cols-2 gap-4"><Field label="Title" required><input className={inputClass} required maxLength="160" value={form.title} onChange={set("title")} /></Field><Field label="Category" required><input className={inputClass} required maxLength="80" value={form.category} onChange={set("category")} /></Field><Field label="Media type"><select className={selectClass} value={form.type} onChange={set("type")}><option value="image">Photo</option><option value="video">Video</option></select></Field><Field label="Status"><select className={selectClass} value={form.status} onChange={set("status")}><option value="draft">Draft</option><option value="published">Published</option></select></Field></div>{form.type === "image" ? imageField("mediaUrl", "Photo") : <><Field label="Video URL" required hint="YouTube or Vimeo watch/share/embed URL"><input className={inputClass} type="url" required value={form.mediaUrl} onChange={set("mediaUrl")} /></Field>{imageField("posterUrl", "Video poster")}</>}<Field label="Alt text" hint="Describe the image for people using screen readers."><input className={inputClass} maxLength="240" value={form.altText} onChange={set("altText")} /></Field><Field label="Description"><textarea className={textareaClass} maxLength="1000" value={form.description} onChange={set("description")} /></Field><Field label="Display order"><input className={inputClass} type="number" min="0" value={form.order} onChange={set("order")} /></Field><div className="flex justify-end gap-3 pt-3 border-t"><button type="button" onClick={() => setModal(false)} className="px-4 py-2 text-sm font-semibold">Cancel</button><button disabled={saving || !!uploading} className="px-5 py-2 rounded-lg bg-[#dc2626] text-white text-sm font-semibold disabled:opacity-50">{saving ? "Saving…" : "Save media"}</button></div></form></Modal>
  </div>;
}
